service: myportfolio
frameworkVersion: '2'

#Services Parameters
custom:
  bucket-name: ${file(./config.json):BUCKET_NAME} #S3 Bucket Name
  table-name: ${file(./config.json):TABLE_NAME} #DynamoDB Table Name
  contact-received-topic: ${file(./config.json):CONTACT_RECEIVED_TOPIC} #SNS Topic Name
  forward-email: ${file(./config.json):FORWARD_EMAIL} #SNS Topic Email Subscriptio
  acm-certificate-arn: ${file(./config.json):ACM_CERT_ARN} #ACM SSL certificate ARN
  hosted-zone-id: ${file(./config.json):HOSTED_ZONE_ID} #Route 53 hosted zone ID

provider: #Basic configuration with IAM Role for the AWS Lambda
  name: aws
  runtime: nodejs12.x
  stage: dev
  lambdaHashingVersion: 20201221
  iam: #IAM Role with DynamoDB write and SNS Topic push permission
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
          Resource:
            Fn::GetAtt: 
              - ContactTable
              - Arn
        - Effect: "Allow"
          Action: 
            - sns:Publish
          Resource: !Ref ContactReceivedTopic
  environment:
    TABLE_NAME: ${self:service}-${self:custom.table-name}
    TOPIC_NAME: !Ref ContactReceivedTopic

#Remove files and folders, those are not needed for lambda package
package:
  individually: true
  excludeDevDependencies: false
  exclude:
    - app/**
    - .gitignore
    - node_modules/**
    - .npmignore

#Lambda functions
functions:
  contact:
    name: ${self:service}-contact
    handler: functions/contact.handler
    description: The lambda function for my portfolio contact form
    events:
      - http:
          path: contact
          method: POST
          cors: true

#AWS Resources
resources:
  Resources:
    S3SiteBucket: #Bucket for host static website
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket-name}
        WebsiteConfiguration:
          IndexDocument: index.html
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - GET
              AllowedOrigins:
                - '*'
              ExposedHeaders:
                - Date
              Id: myCORSRuleId1
              MaxAge: 3600

    ContactTable: #DynamoDB table to store contact details
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:custom.table-name}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    
    OriginAccessIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: !Sub 'OriginAccessIdentity for ${S3SiteBucket}'

    BucketPolicy: #Allow site access from Cloudfront only
      DependsOn: OriginAccessIdentity
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref S3SiteBucket
        PolicyDocument:
          Id: OriginBucketPolicy
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                CanonicalUser: !GetAtt OriginAccessIdentity.S3CanonicalUserId
              Action: 's3:GetObject'
              Resource: !Sub 'arn:aws:s3:::${S3SiteBucket}/*'
    
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - DomainName: ${self:custom.bucket-name}.s3.amazonaws.com
              Id: myS3Origin
              S3OriginConfig:
                  OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${OriginAccessIdentity}'
            - DomainName: !Sub '${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com'
              Id: ApiGatewayOrigin
              CustomOriginConfig:
                  OriginProtocolPolicy: https-only
          Enabled: true
          Comment: 'My Portfolio static website distribution'
          DefaultRootObject: index.html
          Aliases:
            - ${self:custom.bucket-name}
          DefaultCacheBehavior:
            TargetOriginId: myS3Origin
            ViewerProtocolPolicy: https-only
            Compress: true
            DefaultTTL: 3600
            MaxTTL: 3600
            AllowedMethods:
              - GET
              - HEAD
              - DELETE
              - OPTIONS
              - PATCH
              - POST
              - PUT
            CachedMethods:
              - GET
              - HEAD
              - OPTIONS
            ForwardedValues:
              Headers:
                - Accept
                - Referer
                - Authorization
                - Content-Type
              QueryString: true
          CacheBehaviors:
            - PathPattern: /dev/*
              TargetOriginId: ApiGatewayOrigin
              ViewerProtocolPolicy: https-only
              AllowedMethods:
                - GET
                - HEAD
                - POST
                - PUT
                - DELETE
                - OPTIONS
                - PATCH
              ForwardedValues:
                  QueryString: false
            - PathPattern: '*'
              TargetOriginId: myS3Origin
              ViewerProtocolPolicy: redirect-to-https
              ForwardedValues:
                  QueryString: false
          PriceClass: 'PriceClass_100'
          ViewerCertificate:
            AcmCertificateArn: ${self:custom.acm-certificate-arn}
            MinimumProtocolVersion: TLSv1.2_2018
            SslSupportMethod: sni-only        

    ContactReceivedTopic: #SNS Topic for drop a message when new contact is received
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: 'Contact received email'
        TopicName: ${self:service}-${self:custom.contact-received-topic}
        Subscription:
          - Endpoint: ${self:custom.forward-email}
            Protocol: email
    
    WebsiteDNSName: #Register Domain with Route53
      DependsOn: CloudFrontDistribution
      Type: AWS::Route53::RecordSetGroup
      Properties:
        HostedZoneId: ${self:custom.hosted-zone-id}
        RecordSets:
          - Name: ${self:custom.bucket-name}
            Type: A
            AliasTarget:
              DNSName: !GetAtt 
                - CloudFrontDistribution
                - DomainName
              HostedZoneId: 'Z2FDTNDATAQYW2'
    
  #Outputs
  Outputs:
    WebsiteURL:
      Value: !GetAtt
        - S3SiteBucket
        - WebsiteURL
      Description: URL for website hosted on s3
    
    S3BucketSecureURL:
      Value: !Join
        - ''
        - - 'https://'
          - !GetAtt
            - S3SiteBucket
            - DomainName
      Description: Name of S3 bucket to hold website content
    
    CloudFrontDistribuction:
      Value: !Join
        - ''
        - - 'https://'
          - !GetAtt
            - CloudFrontDistribution
            - DomainName
    
    ContactsTable:
      Value: !Ref ContactTable


            
    